var nameList = [
  "Amit Sharma",
  "Sunita Verma",
  "Rajesh Kumar",
  "Meena Singh",
  "Arjun Patel",
  "Pooja Agarwal",
  "Ravi Gupta",
  "Neha Mehta",
  "Suresh Iyer",
  "Anjali Rao",
  "Vikram Desai",
  "Nisha Jain",
  "Rohit Chawla",
  "Kavita Menon",
  "Vijay Nair",
  "Priya Kapoor",
  "Deepak Malhotra",
  "Asha Reddy",
  "Manish Joshi",
  "Sangeeta Das",
  "Harish Bhatia",
  "Ritu Kaur",
  "Sanjay Rathi",
  "Lalita Bhaskar",
  "Naveen Acharya",
  "Rekha Sharma",
  "Mohan Mishra",
  "Tara Goel",
  "Rahul Dubey",
  "Poonam Sinha",
  "Ganesh Kulkarni",
  "Anita Pandey",
  "Shankar Rao",
  "Usha Sen",
  "Ashok Bhattacharya",
  "Geeta Verma",
  "Aakash Reddy",
  "Swati Ghosh",
  "Anil Chauhan",
  "Jyoti Prasad",
  "Kiran Thakur",
  "Nitin Gupta",
  "Sushma Nair",
  "Gopal Yadav",
  "Vandana Kapoor",
  "Yogesh Patel",
  "Amrita Das",
  "Dinesh Sharma",
  "Shweta Joshi",
  "Vikrant Singh",
  "Nikita Sharma",
  "Rahul Khanna",
  "Pallavi Deshmukh",
  "Karan Patel",
  "Sneha Rao",
  "Anupama Sen",
  "Pradeep Reddy",
  "Divya Gupta",
  "Vishal Mehta",
  "Shalini Mishra",
  "Sandeep Malhotra",
  "Priti Sharma",
  "Arvind Rao",
  "Kajal Nair",
  "Ajay Kapoor",
  "Richa Jain",
  "Sameer Verma",
  "Mona Singh",
  "Rakesh Kumar",
  "Aarti Patel",
  "Suraj Gupta",
  "Kirti Sharma",
  "Mahesh Reddy",
  "Nandini Verma",
  "Kunal Thakur",
  "Chitra Rao",
  "Prakash Desai",
  "Sarita Jain",
  "Vijay Chauhan",
  "Snehal Nair",
  "Bharat Patel",
  "Nidhi Malhotra",
  "Aditya Gupta",
  "Rashmi Sen",
  "Siddharth Sharma",
  "Ankita Patel",
  "Rajiv Verma",
  "Komal Desai",
  "Mukesh Joshi",
  "Tina Kapoor",
  "Nilesh Agarwal",
  "Anjana Reddy",
  "Devendra Sharma",
  "Veena Menon",
  "Raghav Gupta",
  "Anita Sharma",
  "Ashwin Kumar",
  "Jaya Singh",
  "Kishore Patel",
  "Preeti Sen",
  "Balaji Rao",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function getRandomMessage() {
  const messages = [
    "Hello! How can I help you today? 😊",
    "I'm doing great, thank you! 👍",
    "Could you please provide more details? 🤔",
    "I'll get back to you shortly. ⏳",
    "Thank you for your patience. 🙏",
    "Is there anything else I can assist you with? 🧐",
    "Have a wonderful day! 🌞",
    "Looking forward to hearing from you. 📨",
    "Let's schedule a meeting for tomorrow. 📅",
    "I'll send you the documents right away. 📄",
    "What time works best for you? ⏰",
    "Can we reschedule our appointment? 🔄",
    "I'm here if you need anything. 🤝",
    "Please hold on while I check. ⏱️",
    "Thank you for reaching out. 💬",
    "I'll be there in 10 minutes. 🚗",
    "Good afternoon! ☀️",
    "I'll let you know as soon as possible. 📣",
    "Take care and stay safe! 🛡️",
    "Can you send me the file? 📁",
    "That sounds like a plan! 📝",
    "Just wanted to say hi! 👋",
    "I'll keep you updated. 🔄",
    "Let's catch up later. ☕",
    "Could you repeat that, please? 🔄",
    "I'm currently unavailable, sorry! 🚫",
    "Let's discuss this further. 🗣️",
    "I appreciate your help. 🙏",
    "Let me know if you need anything. 📲",
    "I'm on my way. 🚶",
    "See you soon! 👀",
    "Thank you for the update. ✔️",
    "How's everything going? 🌈",
    "Can you clarify this part? 🤷",
    "I'm working on it. 🔧",
    "Got it, thanks! 👍",
    "Can we talk now? 🗨️",
    "I'll handle it. 💪",
    "What's your opinion on this? 🧐",
    "I'll call you back. 📞",
    "Let's finalize this today. 📅",
    "I'm available at 3 PM. 🕒",
    "Please send me the details. 📋",
    "Sounds good to me. 😊",
    "Can you check this for me? 🔍",
    "What's the next step? ⏭️",
    "I'm happy to help. 😃",
    "Talk to you later! 👋",
    "I’ll be right with you. ⏳",
    "Yes, that’s correct. ✔️",
    "No problem at all. 😊",
  ];

  const randomIndex = Math.floor(Math.random() * messages.length);
  return messages[randomIndex];
}
